version: "3"
services:
  cronicle:
    container_name: cronicle
    image: cronicle
    restart: always
    hostname: cronicle.example.com
    ports:
      - 127.0.0.1:3012:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/data:/opt/cronicle/data
      - ./data/logs:/opt/cronicle/logs
      - ./data/plugins:/opt/cronicle/plugins
      - ./data/scripts:/opt/cronicle/scripts
    environment:
      - TZ=Australia/Perth
      - CRONICLE_master=1
      - CRONICLE_web_direct_connect=1
      - CRONICLE_web_socket_use_hostnames=1
      - CRONICLE_WebServer__http_port=443